env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    pragma: h
    version: "18"
plugins:
  - react
rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  no-unused-vars:
    - error
    - varsIgnorePattern: h
